// UI-only enhancements. Text localization does not rebuild or reset the 3D scene.
const pairs=[
['页面导航','Page navigation'],['设计工作室','Design studio'],['设计细节','Design details'],['贴近你。','Closer to you.'],['融入每一种日常。','Made for every day.'],['一个无屏幕本体。两种表带长度。你的风格。','One screenless core. Two strap lengths. Your style.'],['可穿戴产品概念','Wearable concept'],['可旋转的 CUSP 3D 模型','Interactive CUSP 3D model'],['交互式 3D','Interactive 3D'],['日常佩戴形态','Everyday wear'],['自动旋转 · 关','Auto-rotate · Off'],['自动旋转 · 开','Auto-rotate · On'],['拖动旋转 · 滚轮或双指缩放','Drag to rotate · Scroll or pinch to zoom'],['正在准备你的 CUSP…','Preparing your CUSP…'],['模型视角','Model views'],['整体','Overview'],['正面','Front'],['侧面','Side'],['贴肤面','Skin side'],['扣具','Buckle'],['换带接口','Connectors'],['相同的感知本体，随佩戴位置与个人风格而变化。','The same sensing core, adapted to how and where you wear it.'],['概念分层','Exploded view'],['滑动探索本体的内部层次。','Slide to explore the layers inside the core.'],['配置你的 CUSP','Configure your CUSP'],['打造你的 CUSP。','Make it yours.'],['从喜欢的材质开始。','Start with the material you love.'],['款式。','Collection. '],['选一种属于你的表达。','Find your expression.'],['选择材质款式','Choose a collection'],['长度。','Length. '],['换一种佩戴方式。','Choose how to wear it.'],['手腕','Wrist'],['上臂','Upper arm'],['短款可调节表带','Short adjustable strap'],['长款可调节表带','Long adjustable strap'],['灵感，成为形态。','An idea, brought to life.'],['查看产品图','View product image'],['产品图','Product image'],['关闭','Close'],['校徽以终稿为准，3D 当前使用校名排版，精确徽章待矢量源文件。','The reference shows the crest. The 3D model uses school-name typography pending a vector crest.'],['保存当前视角','Save this view'],['导出 GLB 模型','Export GLB model'],['导出 GLB','Export GLB'],['正在导出…','Exporting…'],['外观与佩戴概念展示，尚未量产。','An appearance and wearability concept. Not in production.'],['细节，让佩戴更自然。','Details that feel natural.'],['表带可替换，长度可调节。连接隐藏在本体下方。','Replaceable straps. Adjustable fit. Connections concealed beneath the core.'],['同一个本体。','One shared core.'],['手腕与上臂共用接口。更换表带，不改变核心设计。','Wrist and upper-arm straps share one interface. Change the strap, keep the core.'],['贴合，由你调整。','A fit you control.'],['织物穿环回折，皮革针扣调节。余带收纳，保持整洁。','Textile straps fold back through a guide; leather straps use a tang buckle. The tail stays neatly in place.'],['把连接藏起来。','Hidden connections.'],['金属端头衔接带体，隐藏滑轨和底面释放保留完整轮廓。','Metal terminals meet the strap. Concealed rails and underside releases preserve the silhouette.'],['探索结构与设计参数','Explore the structure and design targets'],['织物带尾掀起演示','Textile tail lift'],['返回 3D 视图','Back to the 3D view'],['机身视觉目标','Body appearance target'],['带体宽度','Strap width'],['隐藏滑轨 / 底面释放','Hidden rails / underside release'],['5.5 mm 不含传感凸台。内部空间、公差、锁止强度及密封尚未验证；分层中的器件为占位示意。','5.5 mm excludes the optical island. Packaging, tolerances, retention and sealing are unverified. Exploded components are placeholders.'],['阅读设计说明','Read design notes'],['回到设计工作室','Back to the studio'],
['Forest / 森林绿织物','Forest / Green textile'],['Campus / 紫绿条纹织物','Campus / Striped textile'],['Atelier / 橙色皮革','Atelier / Orange leather'],['镜面银色本体 · 橙色皮革 · 银色针扣','Polished silver · Orange leather · Silver tang buckle'],['拉丝银色本体 · 紫绿中线 · 香槟金扣具','Brushed silver · Purple and green stripe · Champagne hardware'],['拉丝钛银本体 · 森林绿织带 · 暖银扣具','Brushed titanium-silver · Forest textile · Warm-silver hardware'],['针扣穿孔调节，余带由套环收纳。孔距与强度待打样确认。','A tang buckle adjusts through the holes; keepers secure the tail. Hole spacing and strength need prototype validation.'],['穿环回折调节，带尾粘合收纳；滑杆展示掀起状态。','Fold back through the guide and secure the tail. The slider illustrates tail lifting.'],['上盖 / 电池占位 / PCB 占位 / 贴肤底壳','Top cover / Battery placeholder / PCB placeholder / Skin-side housing'],['ATELIER / 针扣与调节孔','ATELIER / Tang buckle and adjustment holes'],['织物 / 穿环回折调节','Textile / Guide and foldback adjustment'],['无屏幕 · 克制的正面','Screenless · A quiet front face'],['机芯贴肤面 · 已隐藏表带','Skin-side core · Strap hidden'],['侧面 · 低矮的机身比例','Side · A low-profile core'],['连接件剖视 · 上轨唇暂时隐藏','Connector cutaway · Upper rail lip hidden']
];
const collections=[['FOREST · 森林绿织物','FOREST · Green textile'],['CAMPUS · 紫绿条纹织物','CAMPUS · Striped textile'],['ATELIER · 橙色皮革','ATELIER · Orange leather']];
for(const [zh,en] of collections){pairs.push([zh,en],[zh+' / 隐藏可替换接口',en+' / Concealed replaceable interface']);for(const [z,e]of [['上臂长带','Upper-arm strap'],['手腕短带','Wrist strap']])pairs.push([zh+' · '+z+'，共用同一本体和隐藏换带接口。',en+' · '+e+'. The same core and concealed strap interface.']);}
for(const [zh,en]of pairs.slice())if(zh.startsWith('Forest /')||zh.startsWith('Campus /')||zh.startsWith('Atelier /'))pairs.push([zh+' 用户终稿',en+' product reference']);
const english=new Map(pairs),chinese=new Map(pairs.map(([z,e])=>[e,z]));
let language=new URLSearchParams(location.search).get('lang')==='zh'?'zh':'en';
const toggle=document.getElementById('languageToggle');
function translate(text){const key=text.trim(),dict=language==='en'?english:chinese;return dict.has(key)?text.replace(key,dict.get(key)):text;}
function localize(){
 const walk=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;
 while(node=walk.nextNode()){if(['SCRIPT','STYLE'].includes(node.parentElement?.tagName)||node.parentElement?.closest('#languageToggle'))continue;const next=translate(node.nodeValue);if(next!==node.nodeValue)node.nodeValue=next;}
 for(const el of document.querySelectorAll('[aria-label],[alt]'))for(const a of ['aria-label','alt']){const old=el.getAttribute(a);if(old){const next=translate(old);if(next!==old)el.setAttribute(a,next);}}
 document.documentElement.lang=language==='en'?'en':'zh-CN';toggle.textContent=language==='en'?'中文':'EN';toggle.setAttribute('aria-label',language==='en'?'切换为中文':'Switch to English');
}
// Disconnect during writes: one observer pass per model/UI update, no feedback loop.
const observer=new MutationObserver(()=>{observer.disconnect();localize();observe();});
function observe(){observer.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','alt']});}
toggle.onclick=()=>{language=language==='en'?'zh':'en';try{localStorage.setItem('cusp-language',language);}catch{}observer.disconnect();localize();observe();};
localize();observe();
const dialog=document.getElementById('productDialog');let opener;
function openImage(event){event.preventDefault();opener=event.currentTarget;const source=document.getElementById('referenceImage');document.getElementById('dialogImage').src=source.src;document.getElementById('dialogImage').alt=source.alt;document.getElementById('dialogCaption').textContent=document.getElementById('colorName').textContent;dialog.showModal();document.body.classList.add('modal-open');}
for(const id of ['imageLink','referenceOpen'])document.getElementById(id).addEventListener('click',openImage);
document.getElementById('closeDialog').onclick=()=>dialog.close();
dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});
dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus();});
