
(()=>{
 const root=document.getElementById('cusp-landscape-23');
 const features={
 metabolic:["Metabolic Wellness, Every Day", "The consumer starting point is everyday metabolic wellness: understand today, relate meals and training to personal context, and review change across weeks and months. Wellness Basic provides low-burden baselines and trends; CGM-enhanced adds measured glucose information to the same account and history. The current product framing supports interpretation and lifestyle assistance.", "Master Story v2.2 · pp. 2 - 4; ToC service direction"],
 mealresponse:["Understand Your Meal Response", "In CGM-enhanced, measured glucose observations can be read alongside meals, post-meal activity and earlier personal episodes. This brings higher-resolution metabolic context into one profile. It does not turn the band into a glucose sensor or establish that a meal caused a particular observed response.", "Master Story v2.2 · pp. 2 - 4; measured external CGM context"],
 gym:['From Gym Floor to Recovery','Future gym setting: connect training records, physiological responses and post-training recovery to support personal plans and periodic review. The image illustrates this setting, not an existing installation or a confirmed gym partnership.','Future Deployment Scenario · User-approved expansion'],
 office:['Wellness at Work','Future office-building setting: build everyday habits around prolonged sitting, movement breaks, meals and sleep. Connect workday context with the user’s own longitudinal history. The image is illustrative and does not document a deployment.','Future Deployment Scenario · User-approved expansion'],
 shifts:['Support Across Shifts','Future shift-work and high-workload setting: place irregular routines, working hours and recovery on the same personal timeline to understand longer-term changes. This is a personal-wellness direction, not an occupational fitness or alertness certification.','Future Deployment Scenario · User-approved expansion'],
 voyage:['Wellness Beyond the Shore','Future long-voyage and onboard setting: record crew members’ routines, activity, meals and physiological context across extended periods at sea, supporting personal health review. The ship image illustrates a proposed context and does not claim a deployed maritime system.','Future Deployment Scenario · User-approved expansion'],
 longitudinal:["Longitudinal intelligence", "Build a personal baseline from physiology, meals, movement, sleep and metabolic references on one timeline. High-quality episodes retain their context after a measurement period ends, so later observations can be compared with the same person’s history. The Master Story identifies this longitudinal core as the shared foundation for consumer wellness and future professional follow-up.", "Master Story v2.2 · pp. 1 - 4; product direction"],
 heart:['Heart rate & HRV','Heart-rate and heart-rate-variability information contribute to physiological context alongside activity, sleep and personal history. This module presents the intended data role, without claiming arrhythmia screening or a validated device measurement specification.','Master Story v2.2 · pp. 2 - 3; existing PPG concept'],
 oxygen:['Blood oxygen · SpO₂','Blood oxygen is included as a sensing direction explicitly supplied by the team in this revision. The Master Story does not list an SpO₂ sensor, measurement accuracy or completed validation. The optical image is a conceptual illustration; colors are symbolic and do not show a final optical design.','Team update · 2026-09-13; generated concept illustration'],
 eda:['Electrodermal activity · EDA','Skin conductance is included as a sensing direction explicitly supplied by the team. It belongs beside other physiological and behavioral context in the longitudinal profile. The Master Story does not freeze an EDA electrode design or validation result. The contact pads and luminous arcs are illustrative, not a final CUSP assembly.','Team update · 2026-09-13; generated concept illustration'],
 temperature:['Skin temperature & movement','Skin-temperature trends and motion sensing (IMU) are part of the existing wearable concept. They can contribute context for the shared personal history. The image shows the concept core; it is not a map of the final sensor placement or a validated temperature-performance claim.','Existing wearable concept README; Master Story · pp. 4 - 6'],
 food:['Photo logging','Photograph a meal, review the entry, edit its details and save it to the journal. Food context joins activity, sleep and physiology on the same personal timeline. The current prototype provides editable photo/manual entries; the pictured bowl is an illustration.','Master Story v2.2 · pp. 1 - 3; existing app requirements'],
 core:['One sensing core. A continuous personal story.','The orange upper-arm wearable is a concept for a low-burden sensing entry point. CUSP’s core value is the longitudinal interpretation service, which can also use compatible third-party devices. The existing enclosure target is 36 × 24 × 5.5 mm, excluding the sensor bump, with a 22 mm strap width; these remain design targets.','Master Story v2.2 · pp. 1 - 3; existing hardware concept; existing V5 hardware concept'],
 ai:['Your AI companion','The golden lion helps translate daily context into understandable guidance and a next action. The current prototype demonstrates a guided assistant flow; the Master Story places long-term personal context at the center of future interpretation rather than generic health Q&A.','Master Story · pp. 3 - 4, 7 - 8; existing app prototype'],
 briefing:['Your daily briefing','Start with status, explanation and a useful next step, then explore the detail. The briefing should place today inside the user’s history and show when the available data is insufficient. The pictured screen is an existing prototype with illustrative entries.','Master Story · pp. 2 - 4; existing app prototype'],
 basic:['Wellness Basic','Low-burden wearable data, meals, movement, sleep and personal history support baselines, trends and contextual interpretation. Current CGM is not required. Basic does not display precise predicted glucose or claim non-invasive glucose measurement.','Master Story v2.2 · pp. 2, 6 - 8'],
 enhanced:['CGM-enhanced','Add measured external CGM data to the same account, timeline and personal profile. This supplies a higher-resolution glucose channel. Any short-horizon prediction is limited to completed validation; the board makes no new performance claim. Earlier high-quality episodes remain part of the user’s history.','Master Story v2.2 · pp. 2 - 4'],
 training:['Training & recovery','Connect training load, recovery, sleep, physiological responses and metabolic context within one personal model. The prototype includes movement sessions and records; deeper joint analysis remains a product direction to validate.','Master Story v2.2 · pp. 2 - 3'],
 quality:["Know the limits.", "Make the available data quality and uncertainty visible. When context is missing or reliability is degraded, reduce or pause output and explain the gap. The future professional review layer should also show evidence provenance and applicability, so a care team can interpret the trajectory in context.", "Master Story v2.2 · pp. 2, 6 - 7; reliability-aware product framing"],
 studio:['Wearable concept & Product Studio','Explore the existing core, wrist/upper-arm configurations, finishes and construction views in 3D. Hardware is the sensing entry point; service-first compatibility remains part of the Master Story. Physical fit, materials and sensor integration still require engineering validation.','Master Story v2.2 · p. 3; existing Product Studio'],
 community:["Better, together.","Gym, campus, content and community are proposed routes into a sustained consumer relationship. Challenges, shared routines and reports can support participation while personal history grows in the longitudinal core. Community is the engagement and growth layer; the photograph illustrates that experience.","Master Story v2.2 · pp. 3, 5, 7 - 8; community concept"]
 };
 const panel=root.querySelector('.cp-detail');let active=null;
 function close(){panel.hidden=true;root.querySelectorAll('[data-feature]').forEach(b=>b.setAttribute('aria-expanded','false'));active=null;}
 root.querySelectorAll('[data-feature]').forEach(button=>button.addEventListener('click',()=>{
  if(active===button.dataset.feature){close();return;}
  active=button.dataset.feature;
  root.querySelectorAll('[data-feature]').forEach(b=>b.setAttribute('aria-expanded',String(b===button)));
  const f=features[active];panel.querySelector('h3').textContent=f[0];panel.querySelector('p').textContent=f[1];panel.querySelector('.cp-source').textContent=f[2];panel.hidden=false;panel.tabIndex=-1;panel.focus({preventScroll:true});panel.scrollIntoView({block:'nearest',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 }));
 function dismiss(){const button=root.querySelector('[aria-expanded="true"]');close();button?.focus();}
 root.querySelector('.cp-close').addEventListener('click',dismiss);root.addEventListener('keydown',e=>{if(e.key==='Escape')dismiss();});
})();

